<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>EDMS1.CommandLog.IntegrationTests</RootNamespace>
        <TargetFramework>net8.0</TargetFramework>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.29" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="NSubstitute" Version="6.0.0" />
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebApplicationExample\WebApplicationExample.csproj" />
    </ItemGroup>

</Project>
