http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    gateway-http:
      rule: "Host(`app.ft.localhost`)"
      service: gateway
      entryPoints: [web]
      middlewares: [redirect-to-https]

    gateway-https:
      rule: "Host(`app.ft.localhost`)"
      service: gateway
      entryPoints: [websecure]
      tls: {}

    keycloak-http:
      rule: "Host(`auth.ft.localhost`)"
      service: keycloak
      entryPoints: [web]
      middlewares: [redirect-to-https]

    keycloak-https:
      rule: "Host(`auth.ft.localhost`)"
      service: keycloak
      entryPoints: [websecure]
      tls: {}

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://financetrack.gateway:8080"

    keycloak:
      loadBalancer:
        servers:
          - url: "http://auth.ft.localhost"

tls:
  certificates:
    - certFile: "/certs/ft-localhost.pem"
      keyFile: "/certs/ft-localhost-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/ft-localhost.pem"
        keyFile: "/certs/ft-localhost-key.pem"