services:
  finance-db:
    image: postgres:16
    container_name: FinanceTrack-financeservice-postgres
    restart: unless-stopped
  
  financetrack.finance.web:
    image: ${DOCKER_REGISTRY-}financetrack-finance
    build:
      args:
        BUILD_CONFIGURATION: Debug
      context: .
      dockerfile: src/FinanceTrack.Finance.Web/Dockerfile
    restart: always